### ISSUE TITLE
buildding pplpy wheels works, but resulting wheels are gmpy2-deficient

### ISSUE THREAD

**Issue by dimpase** [dimpase/pplpy#1]
After installing the wheel built on https://github.com/dimpase/pplpy/actions/runs/1536283468 - I restricted the platform to only build python3.9 manylinux wheels - I get
```
$ python3
Python 3.9.9 (main, Nov 27 2021, 18:06:09) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ppl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dima/.local/lib/python3.9/site-packages/ppl/__init__.py", line 131, in <module>
    from .linear_algebra import (
  File "ppl/linear_algebra.pyx", line 1, in init ppl.linear_algebra
ModuleNotFoundError: No module named 'gmpy2'
>>> 
```
which indicates that ppl does not do the correct thing with the built gmpy2 module.

One way to fix this could be to build wheels for gmpy2 (they are currently not available (they are, with `--pre` option to `pip`).

All fixed at
https://gitlab.com/videlec/pplpy/-/merge_requests/19

**Comment by dimpase** [comment]
@kliem @tobiasdiez @mkoeppe @videlec

**Comment by mkoeppe** [comment]
Looks like `pplpy` forgets to declare `install_requires`.

**Comment by dimpase** [comment]
By the way, see https://github.com/BrianGladman/gmpy2/pull/5 I just made for building PyPI wheels for gmpy2 (manylinux and macOS only, and no Python 3.10).

**Comment by dimpase** [comment]
Still a similar problem after adding `install_requires` with `gmpy2` in it, and other things:
```
$ python3
Python 3.9.9 (main, Nov 27 2021, 18:06:09) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ppl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dima/.local/lib/python3.9/site-packages/ppl/__init__.py", line 131, in <module>
    from .linear_algebra import (
  File "ppl/linear_algebra.pyx", line 1, in init ppl.linear_algebra
TypeError: gmpy2.mpz is not a type object
>>> 
```
(Same error with `wheel` installed, so something is really not OK there.

If instead I first install `gmpy2` wheel from https://github.com/aleaxit/gmpy/actions/runs/1447570556 (or just by `pip install --pre gmpy2 --user`) then all seems to be fine.
(I ran a simple test of ppl wheel).

**Comment by videlec** [comment]
`gmpy2` is a build requirement *and* a run requirement. Here `install_requires` would only possibly fix the second. However, setting it to `['gmpy2']` will probably download the released version and not the beta version needed to run `pplpy`.

**Comment by dimpase** [comment]
I think specifying constraint on the version works.

By the way, why does pplpy depend on mpfr and mpc ?
Can all this be accessed via the new gmpy2 ?

**Comment by videlec** [comment]
I believe that the mpfr and mpc are only gmpy2 dependencies. They can probably be removed in the dependency list of pplpy.

**Comment by dimpase** [comment]
apparently mpfr is in pplpy's headers:
here it what one sees in the logs of last GH Actions run
```
running bdist_wheel 

6179 running build 

6180 running build_py 

6181 creating build 

6182 creating build/lib.linux-x86_64-3.9 

6183 creating build/lib.linux-x86_64-3.9/ppl 

6184 copying ppl/__init__.py -> build/lib.linux-x86_64-3.9/ppl 

6185 copying ppl/mip_problem.pxd -> build/lib.linux-x86_64-3.9/ppl 

6186 copying ppl/polyhedron.pxd -> build/lib.linux-x86_64-3.9/ppl 

6187 copying ppl/bit_arrays.pxd -> build/lib.linux-x86_64-3.9/ppl 

6188 copying ppl/ppl_decl.pxd -> build/lib.linux-x86_64-3.9/ppl 

6189 copying ppl/constraint.pxd -> build/lib.linux-x86_64-3.9/ppl 

6190 copying ppl/congruence.pxd -> build/lib.linux-x86_64-3.9/ppl 

6191 copying ppl/linear_algebra.pxd -> build/lib.linux-x86_64-3.9/ppl 

6192 copying ppl/generator.pxd -> build/lib.linux-x86_64-3.9/ppl 

6193 copying ppl/ppl_shim.hh -> build/lib.linux-x86_64-3.9/ppl 

6194 running build_ext 

6195 building 'ppl.linear_algebra' extension 

6196 creating build/temp.linux-x86_64-3.9 

6197 creating build/temp.linux-x86_64-3.9/ppl 

6198 gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/tmp/pip-build-env-l5tscn1j/overlay/lib/python3.9/site-packages/gmpy2 -Ippl -I/opt/_internal/cpython-3.9.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process -I/tmp/pip-build-env-l5tscn1j/site -I/opt/python/cp39-cp39/lib/python39.zip -I/opt/python/cp39-cp39/lib/python3.9 -I/opt/python/cp39-cp39/lib/python3.9/lib-dynload -I/tmp/pip-build-env-l5tscn1j/overlay/lib/python3.9/site-packages -I/tmp/pip-build-env-l5tscn1j/normal/lib/python3.9/site-packages -I/opt/python/cp39-cp39/include/python3.9 -c ppl/linear_algebra.cpp -o build/temp.linux-x86_64-3.9/ppl/linear_algebra.o 

6199 ppl/linear_algebra.cpp:669:10: fatal error: mpfr.h: No such file or directory 

6200 669 | #include "mpfr.h" 

6201 | ^~~~~~~~ 

6202 compilation terminated. 

6203 error: command '/opt/rh/devtoolset-10/root/usr/bin/gcc' failed with 

```

**Comment by dimpase** [comment]
here: https://github.com/dimpase/pplpy/runs/4414445800

**Comment by dimpase** [comment]
Basically I see the mprf header popping up in 
```
./ppl/mip_problem.cpp:#include "mpfr.h"
./ppl/generator.cpp:#include "mpfr.h"
./ppl/congruence.cpp:#include "mpfr.h"
./ppl/linear_algebra.cpp:#include "mpfr.h"
./ppl/polyhedron.cpp:#include "mpfr.h"
./ppl/constraint.cpp:#include "mpfr.h"
```

which is not a surprise, as in `gmpy2.pxd` one has `cdef extern from "mpfr.h":`
and so in e.g. `ppl/linear_algebra.cpp` one has calls to `mpfr` functions.

**Comment by videlec** [comment]
In order to use the Cython interface of `gmpy2` you do need the `gmp`, `mfpr` and `mpc` headers. This has few to do with `pplpy`. If the headers are not available to your compiler path you can modify the `CLFAGS` accordingly.

**Comment by dimpase** [comment]
I think `gmpy2` ought to provide sub-packages, say one that only provides `gmp`. It's a weird burden on Cython users of `gmpy2` to force them to install `mpfr` and `mpc`, even if they only use `gmp`.

**Comment by dimpase** [comment]
> It's a weird burden on Cython users of `gmpy2` to force them to install `mpfr` and `mpc`, even if they only use `gmp`.

I've reported this to gmpy2, they promised to have a look. Otherwise, all good here.

**Comment by dimpase** [comment]
(see my MR https://gitlab.com/videlec/pplpy/-/merge_requests/19)
